Litt tricky dockerfile oppsett

diff --git a/.github/actions/build-push-docker-image/action.yml b/.github/actions/build-push-docker-image/action.yml
--- a/.github/actions/build-push-docker-image/action.yml
+++ b/.github/actions/build-push-docker-image/action.yml
@@ -33,6 +33,10 @@ inputs:
     required: false
     description: Tag for cache image
     default: ""
+  dockerfile:
+    description: "Dockerfile"
+    required: true
+    default: "Dockerfile"
   docker_context:
     description: "Docker context"
     required: false
@@ -66,6 +70,16 @@ runs:
         project_id: ${{ inputs.project_id }}
         identity_provider: ${{ inputs.identity_provider }}
         team: ${{ inputs.namespace }}
+    - name: Setup environment
+      shell: bash
+      run: |
+        if [ ! -f "${{ inputs.dockerfile }}" ]; then
+          echo "::error ::Dockerfile not found: ${{ inputs.dockerfile }}. Do you need to prepend context or working directory?"
+          exit 1
+        elif [ ! -d "${{ inputs.docker_context }}" ]; then
+          echo "::error ::Docker context not found: ${{ inputs.docker_context }}."
+          exit 1
+        fi
     - name: Docker meta
       if: inputs.bake-action == 'false'
       uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # ratchet:docker/metadata-action@v4
@@ -84,6 +98,7 @@ runs:
       id: build_push
       with:
         context: ${{ inputs.docker_context }}
+        file: ${{ inputs.dockerfile }}
         platforms: ${{ inputs.docker_platforms }}
         pull: true
         push: ${{ inputs.push-image == 'true' }}
